import { Dimensions, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#454955",
    flex: 1,
  },
  title: {
    color: "#454955",
  },
  image: {
    width: 100,
    height: 100,
    position: "absolute",
    alignSelf: "center",
  },
  box: {
    backgroundColor: "#72b01d",
    height: 100,
    position: "absolute",
    top: 0,
  },
  svg: {
    height: 200,
    marginTop: 40,
  },
  formButton: {
    marginTop: 50,
    width: "70%",
  },
  button: {
    backgroundColor: "#72b01d",
    padding: 3,
    opacity: 1,
    alignItems: "center",
    borderRadius: 50,
  },
  textButton: {
    fontSize: 30,
    fontWeight: "500",
    textAlign: "center",
    color: "#454955",
  },
  form: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
    width: "80%",
  },
  nameRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 30,
    width: "60%",
  },
  input: {
    width: "90%",
    backgroundColor: "transparent",
    fontWeight: "100",
    height: 40,
    borderRadius: 50,
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#72b01d",
    marginBottom: 50,
    color: "#f3eff5",
  },
  arrowAnimation: {
    width: 90,
    height: 90,
  },
  genderButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 20,
    gap: 20,
  },
  genderCustom: {
    width: 150,
    height: 150,
  },
  goalContainer: {
    width: "90%",
    alignItems: "center",
  },
  questions: {
    color: "#f3eff5",
    fontSize: 28,
    fontWeight: "600",
    marginBottom: 30,
    textAlign: "center",
    lineHeight: 36,
  },
  optionButton: {
    width: "100%",
    padding: 22,
    borderRadius: 20,
    marginBottom: 16,
    backgroundColor: "#f3eff5",
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#0d0a0b",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 5,
    borderWidth: 2,
    borderColor: "transparent",
  },
  optionButtonSelected: {
    backgroundColor: "#72b01d",
    borderColor: "#3f7d20",
    shadowColor: "#72b01d",
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
    transform: [{ scale: 1.03 }],
  },
  optionIcon: {
    fontSize: 28,
    marginRight: 16,
  },
  optionText: {
    color: "#0d0a0b",
    textAlign: "left",
    fontWeight: "600",
    fontSize: 17,
    flex: 1,
  },
  datePickerContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 20,
  },
  datePickerColumn: {
    flex: 1,
    backgroundColor: "#454955",
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "#3f7d20",
    justifyContent: "center",
    height: 85,
  },
  datePickerLabel: {
    color: "#f3eff5",
    fontSize: 12,
    textAlign: "center",
    paddingVertical: 4,
    backgroundColor: "#3f7d20",
    fontWeight: "600",
    position: "absolute",
    top: 0,
    width: "100%",
  },
  picker: {
    height: 50,
    width: "100%",
    color: "#f3eff5",
    backgroundColor: "transparent",
    marginTop: 20,
  },
  pickerItem: {
    color: "#f3eff5",
    fontSize: 16,
    fontWeight: "bold",
  },
  ageDisplayContainer: {
    marginTop: 25,
    padding: 25,
    backgroundColor: "#72b01d",
    borderRadius: 20,
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#3f7d20",
  },
  ageLabel: {
    color: "#f3eff5",
    fontSize: 16,
    marginBottom: 8,
  },
  ageValue: {
    color: "#fff",
    fontSize: 48,
    fontWeight: "bold",
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#5a5f6d",
    borderRadius: 15,
    paddingHorizontal: 20,
    paddingVertical: 15,
    marginTop: 20,
    width: "80%",
  },
  numericInput: {
    flex: 1,
    fontSize: 36,
    color: "#f3eff5",
    fontWeight: "600",
    textAlign: "center",
  },
  unitLabel: {
    fontSize: 24,
    color: "#72b01d",
    fontWeight: "bold",
    marginLeft: 10,
  },
  weightDisplay: {
    marginTop: 30,
    alignItems: "center",
    backgroundColor: "#72b01d",
    padding: 25,
    borderRadius: 20,
    width: "70%",
    shadowColor: "#72b01d",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  weightIcon: {
    fontSize: 48,
    marginBottom: 10,
  },
  weightValue: {
    fontSize: 42,
    color: "#fff",
    fontWeight: "bold",
  },
  sliderContainer: {
    width: "90%",
    alignItems: "center",
    marginTop: 30,
  },
  sliderWrapper: {
    width: "100%",
    backgroundColor: "#454955",
    borderRadius: 20,
    padding: 25,
    borderWidth: 2,
    borderColor: "#3f7d20",
  },
  sliderValueDisplay: {
    alignItems: "center",
    marginBottom: 25,
  },
  sliderValue: {
    fontSize: 56,
    color: "#72b01d",
    fontWeight: "bold",
  },
  sliderUnit: {
    fontSize: 24,
    color: "#f3eff5",
    marginTop: 5,
  },
  slider: {
    width: "100%",
    height: 40,
    position: "relative",
    justifyContent: "center",
  },
  sliderTrack: {
    position: "absolute",
    width: "100%",
    height: 8,
    borderRadius: 4,
  },
  sliderTrackFilled: {
    position: "absolute",
    height: 8,
    borderRadius: 4,
  },
  sliderThumb: {
    position: "absolute",
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#72b01d",
    borderWidth: 3,
    borderColor: "#f3eff5",
    marginLeft: -12,
    shadowColor: "#0d0a0b",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  sliderLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  sliderLabel: {
    color: "#f3eff5",
    fontSize: 14,
    opacity: 0.7,
  },
  sliderIcon: {
    fontSize: 40,
    marginBottom: 15,
  },
});

